### ISSUE TITLE
-

### ISSUE THREAD

**Issue by 0xD8C4A475** [phpn00b/wbe_csharp_driver#1]

**Comment by IstenesImre** [comment]
More info:

WBM1300 has 2 sensors.
  1. sensor - First
  2. sensor - Deep inside.

When 1. sensor activate, i get:

```
Insert Status: ReadError
        Track 1: 0 -
        Track 2: ReadError -
        Track 3: 0 -
```
So i changed the int the InsertionStatusMessage1370.cs:

```
private bool IsInserted()
{
	return Position1 || Position2;
}

```
To:

private bool IsInserted()
{
			return Position1 && Position2;
}

(When Sensor1 AND Sensor2 active = Card is full deep inside). But same result:

```
Insert Status: ReadError
        Track 1: 0 -
        Track 2: ReadError -
        Track 3: 0 -
```
(I need only Track2)

Thank you

**Comment by omer-kanar** [comment]
For wbm-1370, first track is 0, second track is read error and third truck is 0. What causes this?
